
services:
#  api:
#    build:
#      context: ./api_ml/
#      dockerfile: Dockerfile
#    image: bot:latest
##    networks: ['server-network']
#    ports:
#      - 2406:5000
#    volumes:
#      - ./data/:/app
  swatardbot:
    build:
      platform: linux/arm/v7,linux/amd64,linux/arm/v6
      context: .
      dockerfile: Dockerfile
    image: julienalardot/swatardbot:latest
    ports:
      - 9999:80
    volumes:
      - ./data/:/app/data/
    restart: always
#    environment:
#      DISCORD_TOKEN:
