name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image => Latest
        if: ${{ github.ref_name == 'main' }}
        run: docker build . --file Dockerfile -t julienalardot/swatardbot:${{ github.ref_name }} -t julienalardot/swatardbot:latest

      - name: Build Docker Image => Non-Latest
        if: ${{ github.ref_name != 'main' }}
        run: docker build . --file Dockerfile -t julienalardot/swatardbot:${{ github.ref_name }}

      - name: Login and push to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push => Latest
        if: ${{ github.ref_name == 'main' }}
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: julienalardot/swatardbot:${{ github.ref_name }}, julienalardot/swatardbot:latest


      - name: Build and push => Non-Latest
        if: ${{ github.ref_name == 'main' }}
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: julienalardot/swatardbot:${{ github.ref_name }}
